// apps/web/src/components/SettingsModal.tsx
import { useRouter } from 'next/router'
import { FormEvent, useState } from 'react'

import Modal from '@/components/Modal'
import { initializeGenerator } from '@tinybirdco/mockingbird'

type SettingsModalProps = {
  isOpen: boolean
  onClose: () => void
}

const ENDPOINT_OPTIONS = [
  { label: 'EU (GCP)', value: 'eu_gcp' },
  { label: 'US (GCP)', value: 'us_gcp' },
] as const

export default function SettingsModal({ isOpen, onClose }: SettingsModalProps) {
  const router = useRouter()
  const [error, setError] = useState('')

  const onSubmit = (e: FormEvent) => {
    e.preventDefault()

    const values = new FormData(e.target as HTMLFormElement)
    const { datasource, token, host, eps } = Object.fromEntries(values)

    const isValid = initializeGenerator(
      { datasource, endpoint: host, token },
      true
    )

    if (isValid) {
      const urlParams = new URLSearchParams({
        ...router.query,
        host: host.toString(),
        token: token.toString(),
        datasource: datasource.toString(),
        eps: eps.toString(),
      })
      router.push(`?${urlParams}`)
      onClose()
    } else {
      setError('Invalid configuration')
    }
  }

  const host = (router.query.host as string | undefined) ?? '',
    token = (router.query.token as string | undefined) ?? '',
    datasource = (router.query.datasource as string | undefined) ?? '',
    eps = parseInt((router.query.eps as string | undefined) ?? '1')

  return (
    <Modal isOpen={isOpen} onClose={onClose}>
      <Modal.Content>
        <Modal.Title>Settings</Modal.Title>
        <form
          onSubmit={onSubmit}
          className="grid grid-cols-2 items-center justify-between gap-6"
        >
          <label htmlFor="datasource">Data Source</label>
          <input
            id="datasource"
            name="datasource"
            defaultValue={datasource}
            className="input-base"
          />

          <label htmlFor="token">API Token</label>
          <input
            id="token"
            name="token"
            defaultValue={token}
            className="input-base"
          />

          <label htmlFor="host">Host</label>
          <select
            id="host"
            name="host"
            defaultValue={host}
            className="input-base"
          >
            {ENDPOINT_OPTIONS.map(({ label, value }) => (
              <option key={value} value={value}>
                {label}
              </option>
            ))}
          </select>

          <label htmlFor="eps">EPS</label>
          <input
            id="eps"
            name="eps"
            defaultValue={eps}
            type="number"
            className="input-base"
          />

          {error.length > 0 && <p className="text-red-500">{error}</p>}

          <button
            type="submit"
            className="btn-base bg-tb_emerald text-white col-span-2"
          >
            Save
          </button>
        </form>
      </Modal.Content>
    </Modal>
  )
}

// apps/web/src/components/SettingsModal.svelte
<script lang="ts">
	import { initializeGenerator } from '@tinybirdco/mockingbird';
	import Modal from '../components/Modal.svelte';

	export let on_close: () => void;

	const endpoint_options = [
		{ label: 'EU (GCP)', value: 'eu_gcp' },
		{ label: 'US (GCP)', value: 'us_gcp' }
	];

	const url_params = new URLSearchParams(
		typeof window !== 'undefined' ? window.location.search : ''
	);
	let endpoint = url_params.get('host') || '';
	let token = url_params.get('token') || '';
	let datasource = url_params.get('datasource') || '';
	let eps = parseInt(url_params.get('eps') || '1');
	let error = '';

	function handle_submit() {
		if (initializeGenerator({ datasource, endpoint, token }, true)) {
			const url_params = new URLSearchParams(window.location.search);
			url_params.set('host', endpoint.toString());
			url_params.set('token', token.toString());
			url_params.set('datasource', datasource.toString());
			url_params.set('eps', eps.toString());
			window.history.pushState({}, '', `?${url_params}`);
			on_close();
		} else {
			error = 'Invalid configuration';
		}
	}
</script>

<Modal on:close={on_close}>
	<h3 class="font-bold text-2xl mb-5">Settings</h3>
	<form
		on:submit|preventDefault={handle_submit}
		class="grid grid-cols-2 items-center justify-between gap-6"
	>
		<label for="datasource">Data Source</label>
		<input id="datasource" bind:value={datasource} class="input-base" />

		<label for="token">API Token</label>
		<input id="token" bind:value={token} class="input-base" />

		<label for="endpoint">Endpoint</label>
		<select id="endpoint" bind:value={endpoint} class="input-base">
			{#each endpoint_options as { label, value }}
				<option {value}>{label}</option>
			{/each}
		</select>

		<label for="eps">EPS</label>
		<input id="eps" bind:value={eps} type="number" class="input-base" />
		<p class="text-red-500">{error}</p>
		<button type="submit" class="btn-base bg-tb_emerald text-white col-span-2">Save</button>
	</form>
</Modal>
